### PR TITLE
[WIP] Cleanup SyncLibraryTask

### PR DESCRIPTION
**Pull request by j2ghz**
I've cleaned up SyncLibraryTask and split it into multiple methods. Should I try to follow StyleCop, or try to leave as much code as possible as it is?

Includes: #108 #127

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Hi, thanks ! So this is just  a refactor, no functional change?

**Comment by j2ghz** [comment]
It includes changes from #127, so I'm waiting for that before doing any more cleaning, since it touches the same part. But other than that no, it's just refactor. It's in preparation for #95. If #127 is not accepted I'll try to rebase them to master.

**Comment by LukePulverenti** [comment]
Ok thanks. #127 merged in.

**Comment by j2ghz** [comment]
Should I try to follow StyleCop, or try to leave as much code as possible as it is? I'm asking because of [Ordering Rules](http://stylecop.soyuz5.com/Ordering%20Rules.html), the diff then looks like this: https://gist.github.com/j2ghz/82ec9662a121aeb66a4a0538556a433a/revisions?diff=split

**Comment by LukePulverenti** [comment]
If you're going to continue to make improvements to the plugin then you can do what you're most comfortable with. We don't use style cop but if you want to make non-functional code improvements that is fine.

I think our number one wish list for this plugin would be to just have it work automatically without the need to manually run scheduled tasks.

**Comment by LukePulverenti** [comment]
What do you think?

**Comment by j2ghz** [comment]
About not needing manual tasks? is it even possible to make it better? Trakt won't let us know some data changed and anytime something changes in emby it is posted to trakt. But I will look into it.

**Comment by LukePulverenti** [comment]
Or just continuing with the current work you were planning on. I was really just trying to see if this was still moving. Thanks.

**Comment by LukePulverenti** [comment]
Are these changes stable?

**Comment by LukePulverenti** [comment]
Fyi, I've moved the trakt plugin to it's own dedicated repo: https://github.com/MediaBrowser/trakt

**Comment by j2ghz** [comment]
The changes are untested, but I didn't make any functional changes. It was mostly just extracting methods.

**Comment by LukePulverenti** [comment]
I notice the SyncLibraryTask also updates emby watched states. Does this mean the SyncFromTrakt scheduled task is now obsolete? In other words, we now have two scheduled tasks updating watch data on the Emby side.

**Comment by j2ghz** [comment]
With the #127 option disabled (default, same as before):

SyncLibraryTask modifies Trakt
SyncFromTrakt modifies Emby.

With the option enabled:

SyncLibraryTask resets any watches, that were not scrobbled, but just marked as watched. Scrobbles are processed elsewhere (event handlers), so in this case it doesn't change Trakt data at all.
SyncFromTrakt syncs any changes from Trakt.
(basically, SyncLibraryTask sets emby items as unwatched, SyncFromTrakt sets them as watched)

The tasks could (maybe even should) be merged, but SyncFromTrakt is not obsolete.

**Pull request merged**
